# Generated by Django 4.2 on 2023-06-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='links',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
